name: kedro-tutorial
channels:
- conda-forge
- defaults
dependencies:
- black
- flake8
- ipython
- isort
- jupyter
- jupyter_client
- jupyterlab
- kedro[pandas.CSVDataSet,pandas.ExcelDataSet]
- nbstripout
- pytest-cov
- pytest-mock
- pytest
- wheel
- ipykernel
- wget